default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: load_testing_development
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'postgres') %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', 5432) %>

test:
  <<: *default
  database: load_testing_test
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'postgres') %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', 5432) %>

production:
  <<: *default
  database: load_testing_production
  username: <%= ENV['LOAD_TESTING_DATABASE_USERNAME'] %>
  password: <%= ENV['LOAD_TESTING_DATABASE_PASSWORD'] %>
  host: <%= ENV['LOAD_TESTING_DATABASE_HOST'] %>
  port: <%= ENV['LOAD_TESTING_DATABASE_PORT'] %> 