openapi: "3.0.0"
info:
  version: 0.0.0
  title: VA Mobile API
  license:
    name: MIT
  description: >
    The Department of Veterans Affairs mobile API. All paths are relative to https://api.va.gov/mobile.
servers:
  - url: https://api.va.gov/mobile
paths:
  /mobile/v1/health/immunizations:
    get:
      description: Returns a paginated list of immunization records for given user
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: ./schemas/v1/Immunizations.yml
          description: OK
      security:
        - Bearer: []
      summary: /v1/health/immunizations
