# frozen_string_literal: true
Figaro.require_keys(
  'HOSTNAME',
  'SAML_SP_CERTIFICATE_FILE',
  'SAML_SP_KEY_FILE',
  'REDIS_HOST',
  'REDIS_PORT',
  'DB_ENCRYPTION_KEY',
  'MHV_HOST',
  'MHV_APP_TOKEN',
  'MHV_SM_HOST',
  'MHV_SM_APP_TOKEN',
  'EVSS_BASE_URL',
  'MVI_URL',
  'MVI_CLIENT_CERT_PATH',
  'MVI_CLIENT_KEY_PATH',
  'EVSS_S3_UPLOADS'
)
