# frozen_string_literal: true

ActiveSupport::Inflector.inflections do |inflect|
  inflect.acronym 'AWS'
  inflect.acronym 'AAID'
  inflect.acronym 'BB'
  inflect.acronym 'BGS'
  inflect.acronym 'CC'
  inflect.acronym 'CARMA'
  inflect.acronym 'DOD'
  inflect.acronym 'EMIS'
  inflect.acronym 'EVSS'
  inflect.acronym 'FHIR'
  inflect.acronym 'GIDS'
  inflect.acronym 'GI'
  inflect.acronym 'HCA'
  inflect.acronym 'ICN'
  inflect.acronym 'IHub'
  inflect.acronym 'JWT'
  inflect.acronym 'MDOT'
  inflect.acronym 'MHV'
  inflect.acronym 'MVI'
  inflect.acronym 'NCA'
  inflect.acronym 'PagerDuty'
  inflect.acronym 'PCIU'
  inflect.acronym 'PPIU'
  inflect.acronym 'PPMS'
  inflect.acronym 'PSSG'
  inflect.acronym 'SAML'
  inflect.acronym 'SFTP'
  inflect.acronym 'SM'
  inflect.acronym 'SSOe'
  inflect.acronym 'SSO'
  inflect.acronym 'VAR'
  inflect.acronym 'VAOS'
  inflect.acronym 'VA'
  inflect.acronym 'VBA'
  inflect.acronym 'VIC'
  inflect.acronym 'VC'
  inflect.acronym 'VHA'
  inflect.uncountable 'terms_and_conditions'
end
