# frozen_string_literal: true

ActiveSupport::Inflector.inflections do |inflect|
  inflect.acronym 'AWS'
  inflect.acronym 'CC'
  inflect.acronym 'DOD'
  inflect.acronym 'EMIS'
  inflect.acronym 'EVSS'
  inflect.acronym 'GIDS'
  inflect.acronym 'GI'
  inflect.acronym 'IHub'
  inflect.acronym 'MDOT'
  inflect.acronym 'MHV'
  inflect.acronym 'MVI'
  inflect.acronym 'NCA'
  inflect.acronym 'PagerDuty'
  inflect.acronym 'PPIU'
  inflect.acronym 'SSOe'
  inflect.acronym 'VA'
  inflect.acronym 'VAOS'
  inflect.acronym 'VBA'
  inflect.acronym 'VIC'
  inflect.acronym 'VC'
  inflect.acronym 'VHA'
  inflect.uncountable 'terms_and_conditions'
end
