apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-api
  labels:
    app: vets-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vets-api
  template:
    metadata:
      labels:
        app: vets-api
    spec:
      containers:
        - name: vets-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "Settings.database_url"
              value: "{{ .Values.databaseUrl }}"
            - name: "BUNDLE_ENTERPRISE__CONTRIBSYS__COM"
              value: "{{ .Values.BUNDLE_ENTERPRISE__CONTRIBSYS__COM }}"
            - name: "KMS_KEY_ID"
              value: "insecure-test-key"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: settings-local-yml
              mountPath: /app/config
              subPath: settings.local.yml
      volumes:
        - name: settings-local-yml
          configMap:
            name: settings-local-yml

