apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-api
  labels:
    app: vets-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vets-api
  template:
    metadata:
      labels:
        app: vets-api
    spec:
      containers:
        - name: vets-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "Settings.database_url"
              value: "{{ .Values.databaseUrl }}"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
