kind: IngressRoute
apiVersion: networking.k8s.io/v1
metadata:
  name: vets-website-ingress
spec:
  routes:
    - match: Host("web.{{ .Values.domainName }}")
      kind: Rule
      services:
        - name: vets-website-s3-service
          port: 80
    - match: Host("content.{{ .Values.domainName }}")
      kind: Rule
      services:
        - name: content-s3-service
          port: 80
