kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: vets-website-ingress
spec:
  rules:
    - host: "web.{{ .Values.domainName }}"
      http:
        paths:
          - path: /
            backend:
              service:
                name: vets-website-s3-service
                port:
                  name: http
            pathType: Prefix
    - host: "content.{{ .Values.domainName }}"
      http:
        paths:
          - path: /
            backend:
              service:
                name: content-s3-service
                port:
                  name: http
            pathType: Prefix