#This is needed for mismatching multi-part boundaries -- replacing random boundaries
#Multipart boundaries are most often randomly generated by the HTTP library or browser
#so when VCR tries to match a multipart request with a cassette, the boundaries will be different and the match will fail.
#This was introduced when upgrading to Faraday 0.17.0

#ex -----------boundary=RubyMultipartPost-some_random_boundary_string

MULTIPART_HEADER_MATCHER = %r{^multipart/form-data; boundary=(.+)$}
BOUNDARY_STRING = '-----------RubyMultipartPost'

def normalized_multipart_request(request)
  content_type = (request.headers['Content-Type'] || []).first.to_s

  boundary = MULTIPART_HEADER_MATCHER.match(content_type)[1]

  request.headers['Content-Type'].first.gsub!(boundary, BOUNDARY_STRING)
  request.body.gsub!(boundary, BOUNDARY_STRING)
  request.body.gsub!('RubyMultipartPost--\r\n"', 'RubyMultipartPost--\r\n\r\n"')
  request.headers.delete('Content-Length')
end

