# frozen_string_literal: true

RSpec.shared_context 'shared data' do
  let(:inquiry_params) do
    {
      are_you_the_dependent: 'false',
      attachment_present: 'true',
      branch_of_service: nil,
      city: 'Bogusville',
      contact_method: 'Email',
      country: 'USA',
      daytime_phone: '(470)555-5555',
      dependant_city: nil,
      dependant_country: nil,
      dependant_dob: nil,
      dependant_email: nil,
      dependant_first_name: nil,
      dependant_gender: nil,
      dependant_last_name: nil,
      dependant_middle_name: nil,
      dependant_province: nil,
      dependant_relationship: nil,
      dependant_ssn: nil,
      dependant_state: nil,
      dependant_street_address: nil,
      dependant_zip_code: nil,
      email_address: 'vets.gov.user+229@gmail.com',
      email_confirmation: 'vets.gov.user+229@gmail.com',
      first_name: 'Mark',
      gender: 'M',
      inquiry_about: 'About Me, the Veteran',
      inquiry_category: '75524deb-d864-eb11-bb24-000d3a579c45',
      inquiry_source: 'AVA',
      inquiry_subtopic: nil,
      inquiry_summary: 'string',
      inquiry_topic: '2b2b8586-e764-eb11-bb23-000d3a579c3f',
      inquiry_type: 'Question',
      is_va_employee: 'true',
      is_veteran: 'true',
      is_veteran_an_employee: 'true',
      is_veteran_deceased: 'false',
      level_of_authentication: 'Personal',
      medical_center: nil,
      middle_name: nil,
      preferred_name: 'ABE',
      pronouns: 'He/Him',
      response_type: 'Email',
      street_address2: nil,
      submitter: '42cc2a0a-2ebf-e711-9495-0050568d63d9',
      submitter_dependent: nil,
      submitter_dob: '1950-10-04',
      submitter_gender: 'M',
      submitter_province: nil,
      submitter_question: 'Where can I get a new counselor?',
      submitters_dod_id_edipi_number: '1013590059',
      submitter_ssn: '796104437',
      submitter_state: 'GA',
      submitter_state_of_residency: 'GA',
      submitter_state_of_school: 'GA',
      submitter_state_property: 'GA',
      submitter_street_address: '123 Faker Street',
      submitter_vet_center: '200ESR',
      submitter_zip_code_of_residency: '30058',
      suffix: 'Sr',
      supervisor_flag: 'true',
      va_employee_time_stamp: nil,
      veteran_city: 'Bogusville',
      veteran_claim_number: nil,
      veteran_country: 'USA',
      veteran_date_of_death: nil,
      veteran_dob: '1950-10-04',
      veteran_dod_id_edipi_number: '1013590059',
      veteran_email: 'vets.gov.user+229@gmail.com',
      veteran_email_confirmation: 'vets.gov.user+229@gmail.com',
      veteran_enrolled: 'true',
      veteran_first_name: 'Mark',
      veteran_icn: nil,
      veteran_last_name: 'Webb',
      veteran_middle_name: nil,
      veteran_phone: '(470)555-5555',
      veteran_prefered_name: 'ABE',
      veteran_pronouns: 'He/Him',
      veteran_province: nil,
      veteran_relationship: nil,
      veteran_service_end_date: '01/01/2000',
      veteran_service_number: nil,
      veteran_service_start_date: nil,
      veteran_ssn: '796104437',
      veterans_state: 'GA',
      veteran_street_address: '123 Faker Street',
      veteran_suffix: 'Sr',
      veteran_suite_apt_other: nil,
      veteran_zip_code: '30058',
      who_was_their_counselor: nil,
      your_last_name: 'Webb',
      zip_code: '30058',
      profile: {
        first_name: 'Mark',
        middle_name: nil,
        last_name: 'Webb',
        preferred_name: 'ABE',
        suffix: 'Sr',
        gender: 'M',
        pronouns: 'He/Him',
        country: 'USA',
        street: '123 Faker Street',
        city: 'Bogusville',
        state: 'GA',
        zip_code: '30058',
        province: nil,
        business_phone: nil,
        personal_phone: '(470)555-5555',
        personal_email: 'vets.gov.user+229@gmail.com',
        business_email: 'vets.gov.user+229@gmail.com',
        school_state: 'GA',
        school_facility_code: '15205911',
        service_number: nil,
        claim_number: nil,
        veteran_service_state_date: nil,
        date_of_birth: '1971-12-08',
        edipi: '1013590059'
      },
      school_obj: {
        city: 'Bogusville',
        institution_name: 'ALLATOONA HIGH SCHOOL',
        regional_office: '669cbc60-b58d-eb11-b1ac-001dd8309d89',
        school_facility_code: '15205911',
        state_abbreviation: 'GA'
      },
      attachments: [
        {
          file_name: 'testfile.pdf',
          file_content: 'base 64 string'
        }
      ]
    }
  end
  let(:optionset_cached_data) do
    lambda do |option|
      {
        'inquiryabout' => { Data: [{ Id: 722_310_003, Name: 'A general question' },
                                   { Id: 722_310_000, Name: 'About Me, the Veteran' },
                                   { Id: 722_310_002, Name: 'For the dependent of a Veteran' },
                                   { Id: 722_310_001, Name: 'On behalf of a Veteran' }] },
        'inquirysource' => { Data: [{ Id: 722_310_005, Name: 'Phone' },
                                    { Id: 722_310_004, Name: 'US Mail' },
                                    { Id: 722_310_000, Name: 'AVA' },
                                    { Id: 722_310_001, Name: 'Email' },
                                    { Id: 722_310_002, Name: 'Facebook' }] },
        'inquirytype' => { Data: [{ Id: 722_310_000, Name: 'Compliment' },
                                  { Id: 722_310_001, Name: 'Question' },
                                  { Id: 722_310_002, Name: 'Service Complaint' },
                                  { Id: 722_310_006, Name: 'Suggestion' },
                                  { Id: 722_310_004, Name: 'Other' }] },
        'levelofauthentication' => { Data: [{ Id: 722_310_002, Name: 'Authenticated' },
                                            { Id: 722_310_000, Name: 'Unauthenticated' },
                                            { Id: 722_310_001, Name: 'Personal' },
                                            { Id: 722_310_003, Name: 'Business' }] },
        'suffix' => { Data: [{ Id: 722_310_000, Name: 'Jr' },
                             { Id: 722_310_001, Name: 'Sr' },
                             { Id: 722_310_003, Name: 'II' },
                             { Id: 722_310_004, Name: 'III' },
                             { Id: 722_310_006, Name: 'IV' },
                             { Id: 722_310_002, Name: 'V' },
                             { Id: 722_310_005, Name: 'VI' }] },
        'veteranrelationship' => { Data: [{ Id: 722_310_007, Name: 'Child' },
                                          { Id: 722_310_008, Name: 'Guardian' },
                                          { Id: 722_310_005, Name: 'Parent' },
                                          { Id: 722_310_012, Name: 'Sibling' },
                                          { Id: 722_310_015, Name: 'Spouse/Surviving Spouse' },
                                          { Id: 722_310_004, Name: 'Ex-spouse' },
                                          { Id: 722_310_010, Name: 'GI Bill Beneficiary' },
                                          { Id: 722_310_018, Name: 'Other (Personal)' },
                                          { Id: 722_310_000, Name: 'Attorney' },
                                          { Id: 722_310_001, Name: 'Authorized 3rd Party' },
                                          { Id: 722_310_020, Name: 'Fiduciary' },
                                          { Id: 722_310_006, Name: 'Funeral Director' },
                                          { Id: 722_310_016, Name: 'OJT/Apprenticeship Supervisor' },
                                          { Id: 722_310_013, Name: 'School Certifying Official' },
                                          { Id: 722_310_019, Name: 'VA Employee' },
                                          { Id: 722_310_017, Name: 'VSO' },
                                          { Id: 722_310_014, Name: 'Work Study Site Supervisor' },
                                          { Id: 722_310_011, Name: 'Other (Business)' },
                                          { Id: 722_310_002, Name: 'School Official (DO NOT USE)' },
                                          { Id: 722_310_009, Name: 'Helpless Child' },
                                          { Id: 722_310_003, Name: 'Dependent Child' }] },
        'dependentrelationship' => { Data: [{ Id: 722_310_006, Name: 'Child' },
                                            { Id: 722_310_009, Name: 'Parent' },
                                            { Id: 722_310_008, Name: 'Spouse' },
                                            { Id: 722_310_010, Name: 'Stepchild' },
                                            { Id: 722_310_005, Name: 'Other' }] },
        'responsetype' => { Data: [{ Id: 722_310_000, Name: 'Email' }, { Id: 722_310_001, Name: 'Phone' },
                                   { Id: 722_310_002, Name: 'US Mail' }] }
      }[option]
    end
  end
  let(:translated_payload) do
    { AreYouTheDependent: 'false',
      AttachmentPresent: 'true',
      BranchOfService: nil,
      City: 'Bogusville',
      ContactMethod: 'Email',
      Country: 'USA',
      DaytimePhone: '(470)555-5555',
      DependantCity: nil,
      DependantCountry: nil,
      DependantDOB: nil,
      DependantEmail: nil,
      DependantFirstName: nil,
      DependantGender: nil,
      DependantLastName: nil,
      DependantMiddleName: nil,
      DependantProvince: nil,
      DependantRelationship: nil,
      DependantSSN: nil,
      DependantState: nil,
      DependantStreetAddress: nil,
      DependantZipCode: nil,
      EmailAddress: 'vets.gov.user+229@gmail.com',
      EmailConfirmation: 'vets.gov.user+229@gmail.com',
      FirstName: 'Mark',
      Gender: 'M',
      InquiryAbout: 722_310_000,
      InquiryCategory: '75524deb-d864-eb11-bb24-000d3a579c45',
      InquirySource: 722_310_000,
      InquirySubtopic: nil,
      InquirySummary: 'string',
      InquiryTopic: '2b2b8586-e764-eb11-bb23-000d3a579c3f',
      InquiryType: 722_310_001,
      IsVAEmployee: 'true',
      IsVeteran: 'true',
      IsVeteranAnEmployee: 'true',
      IsVeteranDeceased: 'false',
      LevelOfAuthentication: 722_310_001,
      MedicalCenter: nil,
      MiddleName: nil,
      PreferredName: 'ABE',
      Pronouns: 'He/Him',
      ResponseType: 722_310_000,
      StreetAddress2: nil,
      Submitter: '42cc2a0a-2ebf-e711-9495-0050568d63d9',
      SubmitterDependent: nil,
      SubmitterDOB: '1950-10-04',
      SubmitterGender: 'M',
      SubmitterProvince: nil,
      SubmitterQuestion: 'Where can I get a new counselor?',
      SubmittersDodIdEdipiNumber: '1013590059',
      SubmitterSSN: '796104437',
      SubmitterState: 'GA',
      SubmitterStateOfResidency: 'GA',
      SubmitterStateOfSchool: 'GA',
      SubmitterStateProperty: 'GA',
      SubmitterStreetAddress: '123 Faker Street',
      SubmitterVetCenter: '200ESR',
      SubmitterZipCodeOfResidency: '30058',
      Suffix: 722_310_001,
      SupervisorFlag: 'true',
      VaEmployeeTimeStamp: nil,
      VeteranCity: 'Bogusville',
      VeteranClaimNumber: nil,
      VeteranCountry: 'USA',
      VeteranDateOfDeath: nil,
      VeteranDOB: '1950-10-04',
      VeteranDodIdEdipiNumber: '1013590059',
      VeteranEmail: 'vets.gov.user+229@gmail.com',
      VeteranEmailConfirmation: 'vets.gov.user+229@gmail.com',
      VeteranEnrolled: 'true',
      VeteranFirstName: 'Mark',
      VeteranICN: nil,
      VeteranLastName: 'Webb',
      VeteranMiddleName: nil,
      VeteranPhone: '(470)555-5555',
      VeteranPreferedName: 'ABE',
      VeteranPronouns: 'He/Him',
      VeteranProvince: nil,
      VeteranRelationship: nil,
      VeteranServiceEndDate: '01/01/2000',
      VeteranServiceNumber: nil,
      VeteranServiceStartDate: nil,
      VeteranSSN: '796104437',
      VeteransState: 'GA',
      VeteranStreetAddress: '123 Faker Street',
      VeteranSuffix: 722_310_001,
      VeteranSuiteAptOther: nil,
      VeteranZipCode: '30058',
      WhoWasTheirCounselor: nil,
      YourLastName: 'Webb',
      ZipCode: '30058',
      Profile: { firstName: 'Mark',
                 middleName: nil,
                 lastName: 'Webb',
                 preferredName: 'ABE',
                 suffix: 722_310_001,
                 gender: 'M',
                 pronouns: 'He/Him',
                 country: 'USA',
                 street: '123 Faker Street',
                 city: 'Bogusville',
                 state: 'GA',
                 zipCode: '30058',
                 province: nil,
                 businessPhone: nil,
                 personalPhone: '(470)555-5555',
                 personalEmail: 'vets.gov.user+229@gmail.com',
                 businessEmail: 'vets.gov.user+229@gmail.com',
                 schoolState: 'GA',
                 schoolFacilityCode: '15205911',
                 serviceNumber: nil,
                 claimNumber: nil,
                 veteranServiceStateDate: nil,
                 dateOfBirth: '1971-12-08',
                 edipi: '1013590059' },
      SchoolObj: { City: 'Bogusville',
                   InstitutionName: 'ALLATOONA HIGH SCHOOL',
                   RegionalOffice: '669cbc60-b58d-eb11-b1ac-001dd8309d89',
                   SchoolFacilityCode: '15205911',
                   StateAbbreviation: 'GA' },
      ListOfAttachments: [{ fileName: 'testfile.pdf',
                            fileContent: 'base 64 string' }] }
  end
end
