# Usage
# Create a .env file in this directory with real values for these vars:
# USER=foo
# PASS=bar

### Example call to store data in GenISIS
POST https://vaausapprne60.aac.dva.va.gov/COVID19Service/formdata
Content-Type: application/json
Authorization: Basic {{$dotenv USER}} {{$dotenv PASS}}

< ./example.json
