# frozen_string_literal: true

module ClaimFastTracking
  module DiagnosticCodes
    LIMITED_MOTION_OF_WRIST = 5215
    LIMITATION_OF_MOTION_OF_INDEX_OR_LONG_FINGER = 5229
    LIMITATION_OF_EXTENSION_OF_THE_THIGH = 5251
    FLATFOOT_ACQUIRED = 5276
    HALLUX_VALGUS_UNILATERAL = 5280
    TINNITUS = 6260
    ASTHMA = 6602
    HYPERTENSION = 7101
    SCARS_GENERAL = 7805
    MIGRAINES = 8100
  end
end
