# frozen_string_literal: true

module V0
  class FeatureTogglesController < ApplicationController
    # the feature toggle does not require authentication, but if a user is logged we might use @current_user
    skip_before_action :authenticate
    before_action :load_user

    def index
      if params[:features].present?
        features_params = params[:features].split(',')

        features = features_params.collect do |feature_name|
          underscored_feature_name = feature_name.underscore
          actor_type = FLIPPER_FEATURE_CONFIG['features'].dig(feature_name, 'actor_type')

          { name: feature_name, value: Flipper.enabled?(underscored_feature_name, actor(actor_type)) }
        end
      elsif Rails.env.test?
        features = []

        # returning both camel and snakecase for uniformity on FE
        FLIPPER_FEATURE_CONFIG['features'].collect do |feature_name, values|
          flipper_enabled = Flipper.enabled?(feature_name, actor(values['actor_type']))
          features << { name: feature_name.camelize(:lower),
                        value: flipper_enabled }
          features << { name: feature_name, value: flipper_enabled }
        end
      else
        features = [{:name=>"canUpload1010cgPoa", :value=>false},
          {:name=>"can_upload_10_10cg_poa", :value=>false},
          {:name=>"cernerOverride463", :value=>false},
          {:name=>"cerner_override_463", :value=>false},
          {:name=>"cernerOverride531", :value=>false},
          {:name=>"cerner_override_531", :value=>false},
          {:name=>"cernerOverride648", :value=>false},
          {:name=>"cerner_override_648", :value=>false},
          {:name=>"cernerOverride653", :value=>false},
          {:name=>"cerner_override_653", :value=>false},
          {:name=>"cernerOverride663", :value=>false},
          {:name=>"cerner_override_663", :value=>false},
          {:name=>"cernerOverride668", :value=>false},
          {:name=>"cerner_override_668", :value=>false},
          {:name=>"cernerOverride687", :value=>false},
          {:name=>"cerner_override_687", :value=>false},
          {:name=>"cernerOverride692", :value=>false},
          {:name=>"cerner_override_692", :value=>false},
          {:name=>"cernerOverride757", :value=>false},
          {:name=>"cerner_override_757", :value=>false},
          {:name=>"coeAccess", :value=>true},
          {:name=>"coe_access", :value=>true},
          {:name=>"contactInfoChangeEmail", :value=>false},
          {:name=>"contact_info_change_email", :value=>false},
          {:name=>"covidVaccineRegistration", :value=>false},
          {:name=>"covid_vaccine_registration", :value=>false},
          {:name=>"covidVaccineRegistrationExpanded", :value=>true},
          {:name=>"covid_vaccine_registration_expanded", :value=>true},
          {:name=>"covidVaccineRegistrationFrontend", :value=>false},
          {:name=>"covid_vaccine_registration_frontend", :value=>false},
          {:name=>"covidVaccineRegistrationFrontendCta", :value=>false},
          {:name=>"covid_vaccine_registration_frontend_cta", :value=>false},
          {:name=>"covidVaccineRegistrationFrontendEnableExpandedEligibility", :value=>false},
          {:name=>"covid_vaccine_registration_frontend_enable_expanded_eligibility", :value=>false},
          {:name=>"covidVaccineRegistrationFrontendHideAuth", :value=>false},
          {:name=>"covid_vaccine_registration_frontend_hide_auth", :value=>false},
          {:name=>"covidVaccineSchedulingFrontend", :value=>true},
          {:name=>"covid_vaccine_scheduling_frontend", :value=>true},
          {:name=>"covidVolunteerDelivery", :value=>false},
          {:name=>"covid_volunteer_delivery", :value=>false},
          {:name=>"dashboardShowDashboard2", :value=>true},
          {:name=>"dashboard_show_dashboard_2", :value=>true},
          {:name=>"debtLettersShowLetters", :value=>false},
          {:name=>"debt_letters_show_letters", :value=>false},
          {:name=>"dependencyVerification", :value=>true},
          {:name=>"dependency_verification", :value=>true},
          {:name=>"dependentsManagement", :value=>true},
          {:name=>"dependents_management", :value=>true},
          {:name=>"directDepositVanotify", :value=>false},
          {:name=>"direct_deposit_vanotify", :value=>false},
          {:name=>"educationReportsCleanup", :value=>true},
          {:name=>"education_reports_cleanup", :value=>true},
          {:name=>"evssUploadLimit150mb", :value=>true},
          {:name=>"evss_upload_limit_150mb", :value=>true},
          {:name=>"facilitiesPPMSSuppressCommunityCare", :value=>false},
          {:name=>"facilities_ppms_suppress_community_care", :value=>false},
          {:name=>"facilitiesPPMSSuppressPharmacies", :value=>false},
          {:name=>"facilities_ppms_suppress_pharmacies", :value=>false},
          {:name=>"facilityLocatorCovidVaccineWalkInAvailabilityTextFrontend", :value=>true},
          {:name=>"facility_locator_covid_vaccine_walk_in_availability_text_frontend", :value=>true},
          {:name=>"facilityLocatorLighthouseCovidVaccineQuery", :value=>true},
          {:name=>"facility_locator_lighthouse_covid_vaccine_query", :value=>true},
          {:name=>"facilitiesLocatorMobileCovidOnlineScheduling", :value=>true},
          {:name=>"facilities_locator_mobile_covid_online_scheduling", :value=>true},
          {:name=>"facilityLocatorPPMSForcedUniqueId", :value=>false},
          {:name=>"facility_locator_ppms_forced_unique_id", :value=>false},
          {:name=>"facilityLocatorPPMSLegacyUrgentCareToPosLocator", :value=>false},
          {:name=>"facility_locator_ppms_legacy_urgent_care_to_pos_locator", :value=>false},
          {:name=>"facilityLocatorPPMSUseSecureApi", :value=>false},
          {:name=>"facility_locator_ppms_use_secure_api", :value=>false},
          {:name=>"facilityLocatorPredictiveLocationSearch", :value=>false},
          {:name=>"facility_locator_predictive_location_search", :value=>false},
          {:name=>"facilityLocatorPullOperatingStatusFromLighthouse", :value=>true},
          {:name=>"facility_locator_pull_operating_status_from_lighthouse", :value=>true},
          {:name=>"facilityLocatorRailsEngine", :value=>true},
          {:name=>"facility_locator_rails_engine", :value=>true},
          {:name=>"facilityLocatorShowCommunityCares", :value=>true},
          {:name=>"facility_locator_show_community_cares", :value=>true},
          {:name=>"facilityLocatorShowOperationalHoursSpecialInstructions", :value=>true},
          {:name=>"facility_locator_show_operational_hours_special_instructions", :value=>true},
          {:name=>"findFormsMvpEnhancement", :value=>true},
          {:name=>"find_forms_mvp_enhancement", :value=>true},
          {:name=>"fileUploadShortWorkflowEnabled", :value=>false},
          {:name=>"file_upload_short_workflow_enabled", :value=>false},
          {:name=>"form10182Nod", :value=>true},
          {:name=>"form10182_nod", :value=>true},
          {:name=>"getHelpAskForm", :value=>true},
          {:name=>"get_help_ask_form", :value=>true},
          {:name=>"getHelpMessages", :value=>true},
          {:name=>"get_help_messages", :value=>true},
          {:name=>"gibctEybBottomSheet", :value=>false},
          {:name=>"gibct_eyb_bottom_sheet", :value=>false},
          {:name=>"gibctSchoolRatings", :value=>false},
          {:name=>"gibct_school_ratings", :value=>false},
          {:name=>"inProgressFormCustomExpiration", :value=>true},
          {:name=>"in_progress_form_custom_expiration", :value=>true},
          {:name=>"languageSupport", :value=>true},
          {:name=>"language_support", :value=>true},
          {:name=>"mobileApi", :value=>false},
          {:name=>"mobile_api", :value=>false},
          {:name=>"multipleAddress1010ez", :value=>false},
          {:name=>"multiple_address_10_10ez", :value=>false},
          {:name=>"preEntryCovid19Screener", :value=>false},
          {:name=>"pre_entry_covid19_screener", :value=>false},
          {:name=>"profileSchemaForms", :value=>true},
          {:name=>"profile_schema_forms", :value=>true},
          {:name=>"profileShowReceiveTextNotifications", :value=>true},
          {:name=>"profile_show_receive_text_notifications", :value=>true},
          {:name=>"requestLockedPdfPassword", :value=>true},
          {:name=>"request_locked_pdf_password", :value=>true},
          {:name=>"searchRepresentative", :value=>true},
          {:name=>"search_representative", :value=>true},
          {:name=>"searchTypeaheadEnabled", :value=>true},
          {:name=>"search_typeahead_enabled", :value=>true},
          {:name=>"sharableLink", :value=>true},
          {:name=>"sharable_link", :value=>true},
          {:name=>"show526Wizard", :value=>false},
          {:name=>"show526_wizard", :value=>false},
          {:name=>"showEduBenefits0994Wizard", :value=>false},
          {:name=>"show_edu_benefits_0994_wizard", :value=>false},
          {:name=>"showEduBenefits1990Wizard", :value=>false},
          {:name=>"show_edu_benefits_1990_wizard", :value=>false},
          {:name=>"showEduBenefits1990eWizard", :value=>false},
          {:name=>"show_edu_benefits_1990e_wizard", :value=>false},
          {:name=>"showEduBenefits1990nWizard", :value=>false},
          {:name=>"show_edu_benefits_1990n_wizard", :value=>false},
          {:name=>"showEduBenefits1995Wizard", :value=>false},
          {:name=>"show_edu_benefits_1995_wizard", :value=>false},
          {:name=>"showEduBenefits5490Wizard", :value=>false},
          {:name=>"show_edu_benefits_5490_wizard", :value=>false},
          {:name=>"showEduBenefits5495Wizard", :value=>false},
          {:name=>"show_edu_benefits_5495_wizard", :value=>false},
          {:name=>"showFinancialStatusReport", :value=>true},
          {:name=>"show_financial_status_report", :value=>true},
          {:name=>"showFinancialStatusReportWizard", :value=>true},
          {:name=>"show_financial_status_report_wizard", :value=>true},
          {:name=>"showMedicalCopays", :value=>true},
          {:name=>"show_medical_copays", :value=>true},
          {:name=>"showHealthcareExperienceQuestionnaire", :value=>true},
          {:name=>"show_healthcare_experience_questionnaire", :value=>true},
          {:name=>"showNewGetMedicalRecordsPage", :value=>false},
          {:name=>"show_new_get_medical_records_page", :value=>false},
          {:name=>"showNewRefillTrackPrescriptionsPage", :value=>false},
          {:name=>"show_new_refill_track_prescriptions_page", :value=>false},
          {:name=>"showNewScheduleViewAppointmentsPage", :value=>false},
          {:name=>"show_new_schedule_view_appointments_page", :value=>false},
          {:name=>"showNewSecureMessagingPage", :value=>false},
          {:name=>"show_new_secure_messaging_page", :value=>false},
          {:name=>"showNewViewTestLabResultsPage", :value=>false},
          {:name=>"show_new_view_test_lab_results_page", :value=>false},
          {:name=>"spoolTestingError2", :value=>false},
          {:name=>"spool_testing_error_2", :value=>false},
          {:name=>"spoolTestingError3", :value=>false},
          {:name=>"spool_testing_error_3", :value=>false},
          {:name=>"ssoe", :value=>true},
          {:name=>"ssoe", :value=>true},
          {:name=>"ssoeEbenefitsLinks", :value=>false},
          {:name=>"ssoe_ebenefits_links", :value=>false},
          {:name=>"ssoeInbound", :value=>true},
          {:name=>"ssoe_inbound", :value=>true},
          {:name=>"stemAutomatedDecision", :value=>false},
          {:name=>"stem_automated_decision", :value=>false},
          {:name=>"subform89404192", :value=>true},
          {:name=>"subform_8940_4192", :value=>true},
          {:name=>"vaGlobalDowntimeNotification", :value=>false},
          {:name=>"va_global_downtime_notification", :value=>false},
          {:name=>"vaOnlineScheduling", :value=>true},
          {:name=>"va_online_scheduling", :value=>true},
          {:name=>"vaOnlineSchedulingCancel", :value=>true},
          {:name=>"va_online_scheduling_cancel", :value=>true},
          {:name=>"vaOnlineSchedulingCommunityCare", :value=>true},
          {:name=>"va_online_scheduling_community_care", :value=>true},
          {:name=>"vaOnlineSchedulingDirect", :value=>true},
          {:name=>"va_online_scheduling_direct", :value=>true},
          {:name=>"vaOnlineSchedulingExpressCareNew", :value=>true},
          {:name=>"va_online_scheduling_express_care_new", :value=>true},
          {:name=>"vaOnlineSchedulingFacilitySelectionV22", :value=>true},
          {:name=>"va_online_scheduling_facility_selection_v2_2", :value=>true},
          {:name=>"vaOnlineSchedulingHomepageRefresh", :value=>true},
          {:name=>"va_online_scheduling_homepage_refresh", :value=>true},
          {:name=>"vaOnlineSchedulingProviderSelection", :value=>true},
          {:name=>"va_online_scheduling_provider_selection", :value=>true},
          {:name=>"vaOnlineSchedulingRequests", :value=>true},
          {:name=>"va_online_scheduling_requests", :value=>true},
          {:name=>"vaOnlineSchedulingUnenrolledVaccine", :value=>true},
          {:name=>"va_online_scheduling_unenrolled_vaccine", :value=>true},
          {:name=>"vaOnlineSchedulingVAOSServiceCCAppointments", :value=>true},
          {:name=>"va_online_scheduling_vaos_service_cc_appointments", :value=>true},
          {:name=>"vaOnlineSchedulingVAOSServiceRequests", :value=>true},
          {:name=>"va_online_scheduling_vaos_service_requests", :value=>true},
          {:name=>"vaOnlineSchedulingVAOSServiceVAAppointments", :value=>true},
          {:name=>"va_online_scheduling_vaos_service_va_appointments", :value=>true},
          {:name=>"vaOnlineSchedulingVariantTesting", :value=>true},
          {:name=>"va_online_scheduling_variant_testing", :value=>true},
          {:name=>"vaViewDependentsAccess", :value=>false},
          {:name=>"va_view_dependents_access", :value=>false},
          {:name=>"virtualAgentBotA", :value=>true},
          {:name=>"virtual_agent_bot_a", :value=>true},
          {:name=>"virtualAgentToken", :value=>true},
          {:name=>"virtual_agent_token", :value=>true},
          {:name=>"yellowRibbonMvpEnhancement", :value=>true},
          {:name=>"yellow_ribbon_mvp_enhancement", :value=>true},
          {:name=>"eduForm5490Updates", :value=>true},
          {:name=>"edu_form5490_updates", :value=>true},
          {:name=>"eduForm10203Updates", :value=>true},
          {:name=>"edu_form10203_updates", :value=>true},
          {:name=>"checkInExperienceEnabled", :value=>true},
          {:name=>"check_in_experience_enabled", :value=>true}]
      end

      render json: { data: { type: 'feature_toggles', features: features } }
    end

    def actor(actor_type)
      if actor_type == FLIPPER_ACTOR_STRING
        Flipper::Actor.new(params[:cookie_id])
      else
        @current_user
      end
    end
  end
end
