# frozen_string_literal: true

require 'emis/responses/error_response'
require 'emis/responses/get_combat_pay_response'
require 'emis/responses/get_deployment_response'
require 'emis/responses/get_disabilities_response'
require 'emis/responses/get_guard_reserve_service_periods_response'
require 'emis/responses/get_military_occupation_response'
require 'emis/responses/get_military_service_eligibility_info_response'
require 'emis/responses/get_military_service_episodes_response'
require 'emis/responses/get_military_occupation_response'
require 'emis/responses/get_reserve_drill_days_response'
require 'emis/responses/get_retirement_response'
require 'emis/responses/get_retirement_pay_response'
require 'emis/responses/get_separation_pay_response'
require 'emis/responses/get_unit_information_response'
require 'emis/responses/get_veteran_status_response'
