# frozen_string_literal: true

require_dependency 'emis/responses/error_response'
require_dependency 'emis/responses/get_combat_pay_response'
require_dependency 'emis/responses/get_deployment_response'
require_dependency 'emis/responses/get_disabilities_response'
require_dependency 'emis/responses/get_guard_reserve_service_periods_response'
require_dependency 'emis/responses/get_military_occupation_response'
require_dependency 'emis/responses/get_military_service_eligibility_info_response'
require_dependency 'emis/responses/get_military_service_episodes_response'
require_dependency 'emis/responses/get_military_occupation_response'
require_dependency 'emis/responses/get_reserve_drill_days_response'
require_dependency 'emis/responses/get_retirement_response'
require_dependency 'emis/responses/get_retirement_pay_response'
require_dependency 'emis/responses/get_separation_pay_response'
require_dependency 'emis/responses/get_unit_information_response'
require_dependency 'emis/responses/get_veteran_status_response'
require_dependency 'emis/responses/get_pay_grade_history_response'

module EMIS
  module Responses
  end
end
