name: 'Update DataDog Service Catalog'

on:
  push:
    branches:
      - master
    paths:
      - "datadog-service-catalog/**.yml"

jobs:
  get_files:
    name: 'Get all modified and added files'
    runs-on: ubuntu-latest
    outputs:
      files: ${{steps.one.outputs.files}}
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - id: one
        name: 'Git diff for changes and output matrix of file names'
        run: |
              arr=$(jq -ncR '[inputs]' <<< $(git diff --diff-filter=d --name-only ${{ github.event.before }}...${{ github.sha }} -- "datadog-service-catalog/**.yml"))
              out=$(echo $arr | jq '.[] | select(. !="datadog-service-catalog/datadog-service-catalog.yml")| [.]')
              echo "files=$out" >> $GITHUB_OUTPUT
  update_dd:
    name: 'Update DD with changes'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs:
      - get_files
    strategy:
      matrix:
        file: ${{fromJSON(needs.get_files.outputs.files)}}
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v6
      - id: read_yaml
        name: 'Read in the Service Catalog data'
        uses: mikefarah/yq@master
        with:
          cmd: yq '.' ${{matrix.file}}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_ASSUME_ROLE }}
          aws-region: us-gov-west-1
      - name: Get DD API Key
        uses: department-of-veterans-affairs/action-inject-ssm-secrets@d8e6de3bde4dd728c9d732baef58b3c854b8c4bb
        with:
          ssm_parameter: /dsva-vagov/vets-api/prod/env_vars/DD_API_KEY
          env_variable_name: DD_API_KEY
      - name: Get DD App Key
        uses: department-of-veterans-affairs/action-inject-ssm-secrets@d8e6de3bde4dd728c9d732baef58b3c854b8c4bb
        with:
          ssm_parameter: /dsva-vagov/vets-api/prod/env_vars/DD_APP_KEY
          env_variable_name: DD_APP_KEY
      - name: 'Update Service Catalog in DataDog'
        run: |
          curl --location --request POST 'https://api.ddog-gov.com/api/v2/services/definitions?schema_version=v2.2' \
          --header 'Accept: application/json' \
          --header 'DD-API-KEY: ${{ env.DD_API_KEY }}' \
          --header 'DD-APPLICATION-KEY: ${{ env.DD_APP_KEY }}' \
          --header 'Content-Type: text/plain' \
          --data "${{ steps.read_yaml.outputs.result}}"
