name: Consolidated Security Scan
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
  
    uses: department-of-veterans-affairs/consolidated-security-pipeline/.github/workflows/consolidated-security-pipeline.yml@main
    with:
      image-name: vets-api-pipeline-testing
      aws-region: us-gov-west-1
      run-brakeman-scan: true
      run-codeql-scan: true
      run-trivy-scan: true
    secrets:
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      AWS_ASSUME_ROLE: ${{ vars.AWS_ASSUME_ROLE }}