source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# first: rails plugin new blorgh --mountable --skip-test --dummy-path=spec/dummy
# then: cd blorgh
# then: copy the following line into Gemfile, above the gemspec declaration
gem 'vets_json_schema', git: 'https://github.com/department-of-veterans-affairs/vets-json-schema', branch: 'master'
# then: bundle
# then: rails g rspec:install



# Declare your gem's dependencies in blorgh.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use a debugger
# gem 'byebug', group: [:development, :test]
